//
// Created by Tommy Rushton on 16/02/2023.
//

#ifndef NETJUCE_CONSTANTS_H
#define NETJUCE_CONSTANTS_H

#ifndef AUDIO_BLOCK_SAMPLES
#define AUDIO_BLOCK_SAMPLES 128
#endif

#ifndef NUM_SOURCES
#define NUM_SOURCES 2
#endif

#ifndef DEFAULT_MULTICAST_IP
#define DEFAULT_MULTICAST_IP "226.6.38.226"
#endif

#ifndef DEFAULT_REMOTE_PORT
#define DEFAULT_REMOTE_PORT 18999
#endif

#ifndef DEFAULT_LOCAL_ADDRESS
#define DEFAULT_LOCAL_ADDRESS "192.168.10.10"
#endif

#ifndef DEFAULT_LOCAL_PORT
#define DEFAULT_LOCAL_PORT 18999
#endif


#endif //NETJUCE_CONSTANTS_H
